
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stefano.mureddu
 */
public class Finestra extends javax.swing.JFrame implements ActionListener{
    
    private JTextField ipInizio;
    
    private JTextField ipFine;
    
    private JTextField porte;
    
    private JCheckBox checkA;
    
    private JCheckBox checkB;
    
    private JCheckBox checkC;
    
    private JCheckBox checkD;
    
    private JLabel titolo;
    
    private JLabel ipRange;
    
    private JLabel porteC;
    
    private JPanel title;
    
    private JPanel centro;
    
    private JPanel sotto;
    
    private JButton scan;
    

    /**
     * Creates new form Finestra
     */
    public Finestra() {
        initComponents();
        this.setVisible(true);
        this.setLayout(new BorderLayout());
        title = new JPanel(new GridLayout(0,1));
        titolo = new JLabel("Net Scanner", SwingConstants.CENTER);
        titolo.setFont(new Font("Verdana", Font.PLAIN, 30));
        titolo.setForeground(Color.GREEN);
        ipRange = new JLabel("range di ip da considerare", SwingConstants.CENTER);
        ipRange.setFont(new Font("Verdana", Font.PLAIN, 18));
        title.add(titolo);
        title.add(ipRange);
        centro = new JPanel(new GridLayout(1,2));
        sotto = new JPanel(new GridLayout(8,1));
        ipInizio = new JTextField("", SwingConstants.CENTER);
        ipFine = new JTextField("", SwingConstants.CENTER);
        porte = new JTextField("", SwingConstants.CENTER);
        centro.add(ipInizio);
        centro.add(ipFine);
        porteC = new JLabel("porte da considerare", SwingConstants.CENTER);
        checkA = new JCheckBox("Mostra ip andati a buon fine");
        checkA.setHorizontalAlignment(SwingConstants.CENTER);
        checkB = new JCheckBox("Mostra ip non andati a buon fine");
        checkC = new JCheckBox("Mostra porte andate a buon fine");
        checkD = new JCheckBox("Mostra porte non andate a buon fine");
        checkB.setHorizontalAlignment(SwingConstants.CENTER);
        checkC.setHorizontalAlignment(SwingConstants.CENTER);                   
        checkD.setHorizontalAlignment(SwingConstants.CENTER);
        porteC.setFont(new Font("Verdana", Font.PLAIN, 18));
        scan = new JButton("scanna");
        scan.addActionListener(this);
        sotto.add(porteC);
        sotto.add(porte);
        sotto.add(checkA);
        sotto.add(checkB);
        sotto.add(checkC);
        sotto.add(checkD);
        sotto.add(scan);
        this.add(title, BorderLayout.NORTH);
        this.add(centro, BorderLayout.CENTER);
        this.add(sotto, BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==this.scan){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
